tomcat_download_url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.24/bin/apache-tomcat-8.5.24.tar.gz
tomcat_download_location: /home/ubuntu/tomcat/apache-tomcat-8.5.24.tar.gz
tomcat_user: tomcat
tomcat_group: tomcat
java_path: '/usr/lib/jvm/java-11-openjdk-amd64'
secret: 'cmVmdGtuOjAxOjAwMDAwMDAwMDA6ZnBic0VpVzZxdDF1NDVlakM1dExsWUEyUzBP'
